version: '3'
services:
  service1:
    build:
      context: /publish/Api_A
    image: myapi_a
    ports:
      - 5726:80/tcp
    volumes:
      - /publish/Api_A/appsettings/appsettings5726.json:/app/appsettings.json
  service2:
    image: myapi_a
    ports:
      - 5727:80/tcp
    command: ["dotnet", "/app/Api_A.dll"]
    volumes:
      - /publish/Api_A/appsettings/appsettings5727.json:/app/appsettings.json
  service3:
    image: myapi_a
    ports:
      - 5728:80/tcp
    command: ["dotnet", "/app/Api_A.dll"]
    volumes:
      - /publish/Api_A/appsettings/appsettings5728.json:/app/appsettings.json