version: '3.3'
services:
  service1:
    build:
      context: /publish/MyGateway
    image: mygateway
    ports:
      - 6297:80/tcp
  service2:
    image: mygateway
    ports:
      - 6298:80/tcp
    command: ["dotnet", "/app/MyGateway.dll"]
  service3:
    image: mygateway
    ports:
      - 6299:80/tcp
    command: ["dotnet", "/app/MyGateway.dll"]
  nginx:
    image: nginx:latest
    ports:
      - 8083:80/tcp
    volumes:
      - /publish/MyGateway/nginx.conf:/etc/nginx/nginx.conf
